// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// CudaTileCompiler - Compiler backend for CudaTile

#ifndef TENSOR_IR_COMPILER_CUDATILECOMPILER_H
#define TENSOR_IR_COMPILER_CUDATILECOMPILER_H

#include "tensor_ir/Compiler/Compiler.h"
#include "tensor_ir/Conversion/TensorToCudaTile/Options.h"
#include "tensor_ir/Runtime/IRuntimeKernel.h"
#include "tensor_ir/Support/Status.h"

#include "mlir/IR/BuiltinOps.h"

#include "llvm/ADT/SmallVector.h"

#include "cuda_tile/Bytecode/Common/Version.h"
#include <cassert>
#include <cstdint>
#include <string>
#include <utility>

namespace mlir::nv_tensor_ir::backend::cuda_tile {

/// Selects the requested CUDA Tile device artifact.
enum class CudaTileArtifactKind : uint32_t {
  TileIR = 0,
  Cubin = 1,
};

/// Default TensorIR bytecode target: CUDA Tile's compatibility version, raised
/// to at least 13.3.
///
/// Raw `kCurrentCompatibilityVersion` (13.1 today) cannot serialize features
/// TensorIR commonly emits (e.g. `rounding_mode`, which requires 13.3+). Raw
/// `kCurrentVersion` can exceed the installed driver's JIT support (13.5
/// in-tree today). Taking the max keeps driver compatibility while remaining
/// feature-complete.
inline mlir::cuda_tile::BytecodeVersion getDefaultBytecodeVersion() {
  const auto &compat =
      mlir::cuda_tile::BytecodeVersion::kCurrentCompatibilityVersion;
  // Floor for TensorIR-emitted features such as rounding_mode (not related to
  // kUnifiedBitfieldVersion, which happens to also be 13.3).
  auto minFeatureVersion =
      mlir::cuda_tile::BytecodeVersion::fromVersion(/*verMajor=*/13,
                                                    /*verMinor=*/3,
                                                    /*verTag=*/0);
  assert(minFeatureVersion && "bytecode version 13.3 must be supported");
  return compat < *minFeatureVersion ? *minFeatureVersion : compat;
}

//===----------------------------------------------------------------------===//
// IRDebugOptions - Controls IR dump/load for debug during compilation
//===----------------------------------------------------------------------===//

struct IRDebugOptions {
  /// Dump the lowered CudaTile dialect MLIR to this file path.
  /// Env: TENSOR_IR_DUMP_IR=<path> (0/false/off/no disables)
  std::string dumpCudaTileIRPath;

  /// Dump the Tile IR bytecode to this file path after writeBytecode().
  /// Env: TENSOR_IR_DUMP_TILEIR_BC=<path> (0/false/off/no disables)
  std::string dumpTileIRBCPath;

  /// Print IR to stderr after every pass manager pass.
  /// Ignored when printIRTreeDir is set.
  /// Env: TENSOR_IR_PRINT_IR_AFTER_ALL=1/0, true/false, on/off, yes/no
  bool printIRAfterAll = false;

  /// Write per-pass IR snapshots to this directory (one file per pass).
  /// Takes precedence over printIRAfterAll when both are set.
  /// Env: TENSOR_IR_PRINT_IR_TREE_DIR=<dir> (0/false/off/no disables)
  std::string printIRTreeDir;

  /// Enable pass timing report printed to stderr.
  /// Env: TENSOR_IR_TIMING=1/0, true/false, on/off, yes/no
  bool enableTiming = false;

  /// Load Tile IR bytecode from this file instead of using the generated
  /// bytecode. The MLIR passes still run to extract the kernel name and
  /// argument layout; only the generated bytecode is discarded.
  /// Env: TENSOR_IR_LOAD_TILEIR_BC=<path> (0/false/off/no disables)
  std::string loadTileIRBCPath;
};

//===----------------------------------------------------------------------===//
// CudaTileCompiler - Compiles TensorIR MLIR to CudaTile runtime kernels
//===----------------------------------------------------------------------===//

class CudaTileCompiler : public ICompiler {
public:
  CudaTileCompiler() = default;

  StatusOr<::tensor_ir::rt::IRuntimeKernelPtr>
  compile(mlir::ModuleOp module, const CompileOptions &options) override;

  // XLA integration contract: keep this lightweight and coordinate before
  // changing the signature or semantics.
  bool canCompile(mlir::ModuleOp module,
                  const CompileOptions &options) const override;
};

//===----------------------------------------------------------------------===//
// CudaTileCompileOptions - Compilation options for CudaTile backend
//===----------------------------------------------------------------------===//
class CudaTileCompileOptions : public CompileOptions {
public:
  int32_t ctaCount = 1;
  int32_t warpCount = 4;

  /// Tile sizes per dimension (e.g. {128, 128} for a 2D tiling).
  /// Required for dynamic shape support: these sizes are used to compute
  /// grid dimensions at runtime and to build the kernel argument layout.
  llvm::SmallVector<int32_t> tileSize;

  /// When true, the kernel signature always includes args for ALL tensor
  /// sizes and strides (uniform layout).  When false, only dynamic dims
  /// produce kernel arguments (original behavior).
  bool uniformSignature = false;

  /// IR-level debug options (dump/load intermediate artifacts).
  IRDebugOptions irDebug;

  /// TensorIR-to-CudaTile lowering strategy. Frontends should set this
  /// explicitly instead of relying on process environment.
  CudaTileCodegenStrategy codegenStrategy =
      CudaTileCodegenStrategy::LayoutPropagation;

  /// Maximum number of candidate tiles to keep during layout-propagation
  /// analysis. The value is ignored by the affine-map path.
  int32_t maxTileCandidates = 1;

  /// TileIR bytecode target version. Defaults to
  /// max(kCurrentCompatibilityVersion, 13.3) so generated bytecode stays within
  /// driver-compatible range while supporting TensorIR features that require
  /// 13.3+.
  mlir::cuda_tile::BytecodeVersion bytecodeVersion =
      getDefaultBytecodeVersion();

  /// Requested device artifact. Cubin assembly requires an exact,
  /// arch-conditional compute target; unavailable assemblers fall back to
  /// TileIR bytecode.
  CudaTileArtifactKind artifactKind = CudaTileArtifactKind::TileIR;

  CudaTileCompileOptions(SmTarget computeCapability_)
      : CompileOptions(computeCapability_, CompilerBackend::CudaTile) {}

  CudaTileCompileOptions(SmTarget computeCapability_, int32_t ctaCount_,
                         int32_t warpCount_)
      : CompileOptions(computeCapability_, CompilerBackend::CudaTile),
        ctaCount(ctaCount_), warpCount(warpCount_) {}

  CudaTileCompileOptions(SmTarget computeCapability_, int32_t ctaCount_,
                         int32_t warpCount_,
                         llvm::SmallVector<int32_t> tileSize_)
      : CompileOptions(computeCapability_, CompilerBackend::CudaTile),
        ctaCount(ctaCount_), warpCount(warpCount_),
        tileSize(std::move(tileSize_)) {}

  // To implement LLVM-style polymorphism
  static bool classof(const CompileOptions *opts) {
    return opts->getBackend() == CompilerBackend::CudaTile;
  }

protected:
  Status validateDerived() const override;
  std::string toStringDerived() const override;
  std::string toUniqueStringDerived() const override;
};

} // namespace mlir::nv_tensor_ir::backend::cuda_tile

#endif // TENSOR_IR_COMPILER_CUDATILECOMPILER_H
