// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

//===----------------------------------------------------------------------===//
// TileSelectionPass — resolve, validate, and annotate the final tile shape
//===----------------------------------------------------------------------===//
//
// Pipeline position:
//   LayoutPropagationAnnotation → LayoutPropagationNormalization
//     → TileAnalyzerPass → **TileSelectionPass** → TensorToCudaTileConversion
//
// Purpose:
//   Consumes tile hints from three sources (in priority order) and produces a
//   single, validated "tile_size" DenseI32ArrayAttr on the GraphOp:
//
//     1. tile_size pass option              — forwarded from compilation
//        options (highest priority; allows an explicit caller choice to
//        override a tile embedded in the graph).
//     2. "tile_size" attribute on GraphOp   — set by the graph producer via
//        tensor-ir.
//     3. "tile_candidates" attribute        — generated by TileAnalyzerPass;
//        the pass picks tile_candidates[0] (best-scored candidate).
//        TileAnalyzerPass guarantees this attribute is present whenever
//        an iteration space exists — it falls back to a conservative tile
//        when its scoring tracks produce nothing — so this source covers
//        both the analyzer-driven and fallback paths.
//
//   If none of the above are available the pass emits an error.
//
// Validation:
//   When the "iteration_space" attribute is present on the graph terminator
//   (set by LayoutPropagationNormalizationPass), the selected tile is checked
//   for rank match and per-dimension validity (power-of-2, within bounds).
//   Invalid tiles cause the pass to emit a diagnostic and fail.
//
// Guarantees to downstream passes:
//   • "tile_size" is always present on GraphOp after this pass succeeds.
//   • "tile_candidates" is removed (cleanup — consumed by this pass).
//   • The tile shape has been validated against the iteration space when that
//     information is available.
//   • TensorToCudaTileConversionPass reads "tile_size" from the GraphOp
//     attribute and does not need its own tile-size pass option for the
//     LayoutPropagation codegen strategy.
//
// Failure modes:
//   • No tile source available → error with list of expected sources.
//   • tile_candidates is empty or malformed → error.
//   • Tile rank does not match iteration space rank → error with both shapes.
//   • Tile dimension is not power-of-2 or exceeds shape → error.
//
//===----------------------------------------------------------------------===//

#include "tensor_ir/Analysis/TileAnalyzer.h"
#include "tensor_ir/Analysis/TileCandidateGenerator.h"
#include "tensor_ir/Dialect/TensorIR.h"
#include "tensor_ir/Dialect/TensorIRAttrs.h"
#include "tensor_ir/Transform/Passes.h"

#include "mlir/IR/BuiltinAttributes.h"

#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Debug.h"

#define DEBUG_TYPE "tile-selection"

namespace mlir::nv_tensor_ir {

#define GEN_PASS_DEF_TILESELECTIONPASS
#include "tensor_ir/Transform/Passes.h.inc"

namespace {

/// Extract the iteration space shape from the "iteration_space" attribute on
/// the graph's terminator via LayoutSourceAttrInterface::getShape().
/// Returns failure if the attribute is absent or does not implement the
/// interface.
static FailureOr<LayoutSourceAttrInterface>
extractIterationSpace(GraphOp graphOp) {
  Operation *terminator = graphOp.getBody()->getTerminator();
  if (!terminator) {
    return failure();
  }

  auto layoutSource = terminator->getAttrOfType<LayoutSourceAttrInterface>(
      TensorIRDialect::getIterationSpaceAttrName());
  if (!layoutSource) {
    return failure();
  }

  return layoutSource;
}

/// Check if the iteration_space shape has any dynamic dimensions.
static bool hasDynamicDims(ArrayRef<DimSize> shape) {
  return llvm::any_of(shape, [](DimSize d) { return d <= 0; });
}

struct TileSelectionPass
    : public impl::TileSelectionPassBase<TileSelectionPass> {

  using TileSelectionPassBase::TileSelectionPassBase;

  void runOnOperation() override {
    GraphOp graphOp = getOperation();
    MLIRContext *ctx = graphOp.getContext();

    // ── Step 1: Resolve tile shape (priority order) ─────────────────
    SmallVector<int32_t> selectedTile;

    // Source 1: tile_size pass option (from compilation options)
    if (!tile_size.empty()) {
      selectedTile.assign(tile_size.begin(), tile_size.end());
      LLVM_DEBUG(llvm::dbgs()
                 << "TileSelectionPass: using tile_size from pass option: "
                 << vectorToString(selectedTile) << "\n");
    }
    // Source 2: "tile_size" attribute on GraphOp (from tensor-ir)
    else if (auto tileSizeAttr = graphOp->getAttrOfType<DenseI32ArrayAttr>(
                 TensorIRDialect::getTileSizeAttrName())) {
      auto values = tileSizeAttr.asArrayRef();
      selectedTile.assign(values.begin(), values.end());
      LLVM_DEBUG(llvm::dbgs()
                 << "TileSelectionPass: using tile_size attr from GraphOp: "
                 << vectorToString(selectedTile) << "\n");
    }
    // Source 3: "tile_candidates" attribute on GraphOp (from TileAnalyzerPass)
    else if (auto candidatesAttr = graphOp->getAttrOfType<ArrayAttr>(
                 TensorIRDialect::getTileCandidatesAttrName())) {
      if (candidatesAttr.empty()) {
        graphOp.emitError("tile_candidates is empty and no tile shape provided "
                          "through tensor-ir or compilation options");
        return signalPassFailure();
      }
      auto best = dyn_cast<DenseI32ArrayAttr>(candidatesAttr[0]);
      if (!best) {
        graphOp.emitError("tile_candidates[0] is not a DenseI32ArrayAttr");
        return signalPassFailure();
      }
      auto values = best.asArrayRef();
      selectedTile.assign(values.begin(), values.end());
      LLVM_DEBUG(llvm::dbgs() << "TileSelectionPass: using tile_candidates[0]: "
                              << vectorToString(selectedTile) << "\n");
    }
    // No source available: fail. TileSelectionPass must expect at least one
    // tile candidate.
    else {
      graphOp.emitError("No tile shape source available. Expected one of: "
                        "tile_size pass option, \"tile_size\" attr on GraphOp, "
                        "or \"tile_candidates\" from TileAnalyzerPass");
      return signalPassFailure();
    }

    // ── Step 2: Verify tile against iteration space ─────────────────
    auto rootLayout = extractIterationSpace(graphOp);
    if (succeeded(rootLayout)) {
      auto iterSpaceShape = rootLayout->getShape();
      if (static_cast<int64_t>(selectedTile.size()) !=
          static_cast<int64_t>(iterSpaceShape.size())) {
        graphOp.emitError()
            << "Selected tile " << vectorToString(selectedTile)
            << " is not valid for iteration space "
            << vectorToString(iterSpaceShape) << " — rank mismatch (tile rank "
            << selectedTile.size() << " vs iteration space rank "
            << iterSpaceShape.size() << ")";
        return signalPassFailure();
      }

      // Skip per-dim validation when the iteration space has dynamic dims
      // (tile validity can only be checked at runtime).
      if (!hasDynamicDims(iterSpaceShape)) {
        GpuArchitecture gpu(/*warp_size=*/32, /*cache_line=*/128);
        TileCandidateGenerator generator(gpu, /*maxCandidates=*/1);
        if (!generator.isValidTile(selectedTile, iterSpaceShape)) {
          graphOp.emitError()
              << "Selected tile " << vectorToString(selectedTile)
              << " is not valid for iteration space "
              << vectorToString(iterSpaceShape);
          return signalPassFailure();
        }
      }
    }

    // ── Step 3: Update IR annotations ──────────────────────────────
    graphOp->removeAttr(TensorIRDialect::getTileCandidatesAttrName());
    graphOp->setAttr(TensorIRDialect::getTileSizeAttrName(),
                     DenseI32ArrayAttr::get(ctx, selectedTile));

    LLVM_DEBUG(llvm::dbgs() << "TileSelectionPass: set tile_size = "
                            << vectorToString(selectedTile) << " on "
                            << graphOp.getSymName() << "\n");
  }
};

} // namespace

} // namespace mlir::nv_tensor_ir
