// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// IRuntimeKernel - Pure interface for compiled GPU kernels

#ifndef TENSOR_IR_RUNTIME_IRUNTIMEKERNEL_H
#define TENSOR_IR_RUNTIME_IRUNTIMEKERNEL_H

#include "tensor_ir/Runtime/Types.h"
#include "tensor_ir/Support/Status.h"

#include <memory>

namespace tensor_ir::rt {

//===----------------------------------------------------------------------===//
// IRuntimeKernel - Pure interface for compiled GPU kernels
//
// Follows TVM FFI calling convention with PackedArgs.
// Implementations are generated by the compiler.
//===----------------------------------------------------------------------===//

class IRuntimeKernel {
public:
  virtual ~IRuntimeKernel() = default;

  /// Get runtime kernel name (for debugging/logging)
  virtual const std::string &name() const = 0;

  //=========================================================================
  // Initialization (lazy loading)
  //=========================================================================

  /// Initialize runtime state in the current CUDA context.
  /// This may trigger lazy loading of CUDA modules and should be called before
  /// the first launch.
  /// Thread-safe: can be called from multiple threads.
  virtual Status initializeRuntimeState() const = 0;

  /// Unload runtime state (optional cleanup)
  virtual Status unloadRuntimeState() const = 0;

  //=========================================================================
  // Validation
  //=========================================================================

  /// Check if the runtime kernel supports the given problem.
  /// Validates argument shapes, dtypes, alignment, etc.
  virtual Status checkSupport(PackedArgs args) const = 0;

  //=========================================================================
  // Workspace
  //=========================================================================

  /// Query workspace size required for given arguments.
  virtual size_t queryWorkspaceSize(PackedArgs args) const = 0;

  //=========================================================================
  // Execution
  //=========================================================================

  /// Launch the runtime kernel.
  virtual Status launch(PackedArgs args, Workspace workspace,
                        Stream stream) const = 0;
};

//===----------------------------------------------------------------------===//
// Owning pointer types
//===----------------------------------------------------------------------===//

using IRuntimeKernelPtr = std::unique_ptr<IRuntimeKernel>;
using IRuntimeKernelConstPtr = std::unique_ptr<const IRuntimeKernel>;

} // namespace tensor_ir::rt

#endif // TENSOR_IR_RUNTIME_IRUNTIMEKERNEL_H
