// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

//===-- TensorOps.td - Tensor operation definitions ---*- tablegen -*-===//
//
#ifndef PYTHON_BINDINGS_TENSOR_IR_TENSOR_DIALECT_TENSOR_OPS
#define PYTHON_BINDINGS_TENSOR_IR_TENSOR_DIALECT_TENSOR_OPS

include "tensor_ir/Dialect/TensorOps.td"

#endif // PYTHON_BINDINGS_TENSOR_IR_TENSOR_DIALECT_TENSOR_OPS
