include_guard(GLOBAL)

function(tensor_ir_configure_native_tablegen)
  project(TENSOR_IR LANGUAGES CXX)
  if(NOT LLVM_ROOT)
    message(FATAL_ERROR "LLVM_ROOT is required to build native tensor_ir-tblgen")
  endif()
  set(LLVM_DIR "${LLVM_ROOT}/lib/cmake/llvm")
  set(MLIR_DIR "${LLVM_ROOT}/lib/cmake/mlir")
  find_package(LLVM REQUIRED CONFIG NO_DEFAULT_PATH)
  find_package(MLIR REQUIRED CONFIG NO_DEFAULT_PATH)
  list(APPEND CMAKE_MODULE_PATH "${LLVM_CMAKE_DIR}" "${MLIR_CMAKE_DIR}")
  include(AddLLVM)
  include(AddMLIR)
  include(TableGen)
  include(GNUInstallDirs)
  include_directories(${LLVM_INCLUDE_DIRS} ${MLIR_INCLUDE_DIRS})
  set(LLVM_RUNTIME_OUTPUT_INTDIR "${CMAKE_BINARY_DIR}/bin")
  set(LLVM_LIBRARY_OUTPUT_INTDIR "${CMAKE_BINARY_DIR}/lib")
  add_subdirectory(tools/tensor_ir-tblgen)
endfunction()

function(tensor_ir_configure_cross_compile)
  include(CrossCompile)
  set(LLVM_USE_HOST_TOOLS ON PARENT_SCOPE)
  if(NOT LLVM_PROJECT_NATIVE_BUILD_DIR)
    message(FATAL_ERROR "LLVM_PROJECT_NATIVE_BUILD_DIR is required")
  endif()
  set(native_toolchain_args)
  if(NATIVE_C_COMPILER)
    list(APPEND native_toolchain_args -DCMAKE_C_COMPILER=${NATIVE_C_COMPILER})
  endif()
  if(NATIVE_CXX_COMPILER)
    list(APPEND native_toolchain_args -DCMAKE_CXX_COMPILER=${NATIVE_CXX_COMPILER})
  endif()
  set(native_project_name "${PROJECT_NAME}")
  llvm_create_cross_target(${native_project_name} NATIVE "" Release
    -DLLVM_ROOT=${LLVM_PROJECT_NATIVE_BUILD_DIR}
    ${native_toolchain_args})
  set(${native_project_name}_NATIVE_BUILD
      "${${native_project_name}_NATIVE_BUILD}" PARENT_SCOPE)
  set(${native_project_name}_NATIVE_STAMP
      "${${native_project_name}_NATIVE_STAMP}" PARENT_SCOPE)
endfunction()
