// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef TENSOR_IR_CONVERSION_TENSORTOCUDATILE_TENSORTOCUDATILE_H
#define TENSOR_IR_CONVERSION_TENSORTOCUDATILE_TENSORTOCUDATILE_H

#include "tensor_ir/Conversion/TensorToCudaTile/Options.h"
#include "tensor_ir/Dialect/TensorIR.h"

#include "mlir/Pass/Pass.h" // IWYU pragma: keep
#include "mlir/Transforms/DialectConversion.h"

namespace mlir::nv_tensor_ir {

#define GEN_PASS_DECL
#define GEN_PASS_REGISTRATION
#include "tensor_ir/Conversion/TensorToCudaTile/Passes.h.inc"

/// Temporary module-level attribute used to surface tile sizes resolved by
/// TensorToCudaTileConversionPass after it erases the GraphOp.
inline constexpr const char *kResolvedTileSizeAttrName =
    "tensor_ir.resolved_tile_size";

/// Temporary module-level attribute preserving the normalized iteration-space
/// shape after TensorToCudaTileConversionPass erases the GraphOp.
inline constexpr const char *kResolvedIterationSpaceShapeAttrName =
    "tensor_ir.resolved_iteration_space_shape";

namespace tensor_to_cuda_tile {

// Default alignment in CUDA is 256B, but we cannot assume that the pointers
// are aligned. The TensorIR must include the "alignment" attribute to enable
// vectorized loads/stores in the CUDA Tile lowering.
constexpr int64_t kDefaultPointerAlignment = 1;

/// Conversion state interface that provides tile values and shapes in the
/// context of the graph and the operation being processed.
class ConversionState {
public:
  virtual ~ConversionState() = default;

  /// Prepare the conversion state for a graph conversion.
  virtual LogicalResult start(GraphOp graphOp) = 0;

  /// Prepare the conversion state for an operation conversion.
  virtual LogicalResult update(ConversionPatternRewriter &rewriter,
                               Operation *op) = 0;

  /// Get the tile for an operand.
  virtual Value getTile(Value operand) = 0;

  /// Get the tile shape for the current iteration space.
  virtual ArrayRef<int64_t> getTileShape() = 0;

  /// Get per-dimension block index values for the current iteration space.
  /// Non-empty only for the layout-propagation codegen strategy.
  virtual ArrayRef<Value> getIndexValues() const { return {}; }

  /// Get the resolved tile size to synchronize runtime launch metadata.
  virtual ArrayRef<int64_t> getResolvedTileSize() { return {}; }

  /// Get current block structure for operations that modify the iteration
  /// space (concatenation, reduction, matmul).
  virtual const struct BlockStructure *getBlockStructure() const {
    return nullptr;
  }
};

/// Conversion pattern base class that provides access to the conversion state.
template <typename OpTy>
class ConversionPattern : public OpConversionPattern<OpTy> {
public:
  ConversionPattern(ConversionState &state, const TypeConverter &typeConverter,
                    MLIRContext *ctx, PatternBenefit benefit = 1)
      : OpConversionPattern<OpTy>(typeConverter, ctx, benefit), state(state) {}

protected:
  ConversionState &state;
};

/// Information about the iteration space, constructed during the `GraphOp`
/// conversion before converting the rest of the graph operations.
struct IterationSpace {
  // Insertion point for the operations in the iteration space.
  // The same block may be used for multiple iteration spaces.
  Block *insertionBlock;

  // Shape of the tile for the iteration space.
  SmallVector<int64_t> tileShape;

  // Values used to index the loads (integer type).
  // Has the same rank as the tile shape.
  SmallVector<Value> indexValues;

  // Values loaded from the tensor sources (tile type).
  llvm::MapVector<TensorSourceAttr, Value> loadedTiles;
};

/// Information about the block structure generated by an operation that
/// modifies the iteration space (concatenation, reduction, matmul).
struct BlockStructure {
  // Sentinel used in `iterationSpaceIndexForOperand` for an operand that feeds
  // no iteration space (a concatenate operand pruned away by a slice).
  static constexpr int kNoIterationSpace = -1;

  // The iteration spaces this owner op creates -- one entry per layout source
  // (not per operand: a pruned concatenate has fewer sources than operands, and
  // a user-defined reduction has one shared space for all operands). Each entry
  // is the concrete loop/branch context for one source: its insertion block,
  // tile shape, index values, and loaded tiles (see `IterationSpace`).
  SmallVector<IterationSpace> iterationSpaces;

  // Tile values produced by the block structure.
  // May be empty if no blocks were generated.
  SmallVector<Value> yieldValues;

  // The operand -> iteration-space relation for the owner op, and the single
  // source of truth for it. Sized to the owner's operand count; entry `p` is
  // the index into `iterationSpaces` that operand `p` feeds, or
  // `kNoIterationSpace` when the operand feeds none. Indices (not
  // `IterationSpace *`) are stored because a `BlockStructure` is moved into
  // (and rehashed within) a `DenseMap`, which relocates `iterationSpaces` and
  // would dangle any element pointer; indices stay valid across the move.
  SmallVector<int> iterationSpaceIndexForOperand;
};

/// ----- Implemented in `AffineMapImpl.cpp` -----------------------------------

/// State factory for the "affine_map" codegen strategy.
std::unique_ptr<ConversionState>
createAffineMapConversionState(MLIRContext *context,
                               const TypeConverter &typeConverter,
                               const TensorToCudaTilePipelineOptions &options);

/// ----- Implemented in `LayoutPropagationImpl.cpp` ---------------------------

/// State factory for the "layout_propagation" codegen strategy.
std::unique_ptr<ConversionState> createLayoutPropagationConversionState(
    MLIRContext *context, const TypeConverter &typeConverter,
    Attribute optimizationHints, bool uniformSignature,
    int64_t reductionTileSize, bool enableExperimentalCudaTileOps);

/// Verify that the layout-propagation TensorIR-to-CudaTile conversion can lower
/// the whole graph, without running the IR-materializing conversion driver.
/// Composes the graph-level checks (`verifyGraphLevelLayoutPropLowerable`) with
/// a per-op walk that applies the same per-op legality validators the
/// conversion patterns use, plus the attribute-level checks. This is the
/// pre-flight feasibility check used by the backend's `canCompile`.
///
/// Preconditions: Phase 1 (graph analysis) and Phase 2 (tile selection) must
/// have already run on the graph, so the relevant attributes are present.
LogicalResult verifyLayoutPropLowerable(GraphOp graphOp);

} // namespace tensor_to_cuda_tile
} // namespace mlir::nv_tensor_ir

#endif // TENSOR_IR_CONVERSION_TENSORTOCUDATILE_TENSORTOCUDATILE_H
